songmemes = ['https://youtu.be/8CvqmD0CZao', 
'https://youtu.be/ETfiUYij5UE', 
'https://www.youtube.com/watch?v=K5tVbVu9Mkg', 
'https://www.youtube.com/watch?v=9a4exztEy6g', 
'https://www.youtube.com/watch?v=1w5_IktEDOI', 
'https://www.youtube.com/watch?v=FGiwDwmoJLk', 
'https://www.youtube.com/watch?v=rEM6zENiupo', 
'https://www.youtube.com/watch?v=ZZ5LpwO-An4', 
'https://www.youtube.com/watch?v=QBPVPbLjCHw', 
'https://www.youtube.com/watch?v=d6K3T63w8AA', 
'https://youtu.be/d6K3T63w8AA', 
'https://youtu.be/WM-fTkO6BI4', 
'https://www.youtube.com/watch?v=f3IgwLT_mYc', 
'https://www.youtube.com/watch?v=iY1s6qpGqEw']